version: '3.8'

services:
  symfony:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      DATABASE_URL: mysql://app:app@database:3306/hyperchat?serverVersion=8.0.32&charset=utf8mb4
      APP_ENV: dev
      APP_DEBUG: 1
    restart: unless-stopped

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hyperchat
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
